vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        videos:
            uri_prefix: /videos
            upload_destination: '%kernel.project_dir%/public/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
